#!/usr/bin/env bash

# Do 5 minutes stuff

echo "install rvm system wide rvm"
sudo \curl -L https://get.rvm.io | sudo bash

echo "set rvm at /etc/sudoers"
export rvmsudo_secure_path=1

echo "install required softwares"
rvmsudo rvm requirements


sudo apt-get openssl libreadline6 libreadline6-dev libssl-dev sqlite3 

echo "Install ruby 1.9.3 unless you want ruby 2.0"
rvm install 1.9.3

rvm use 1.9.3 --default

rvm rubygems current

gem install rails --no-ri --no-rdoc

gem install passenger

export rvmsudo_secure_path=1

rvmsudo passenger-install-nginx-module

rails new webapp1

sudo nano /opt/nginx/conf/nginx.conf
server { 
  listen 80; 
  server_name example.com; 
  passenger_enabled on; 
  root /home/root/webapp1/public; 
}


sudo service nginx start 

If service doesn't exist follow http://wiki.nginx.org/Nginx-init-ubuntu
